<project>
    <target name="init">
        <tstamp/>
    </target>
    <target name="buildMod" depends="init">
        <zip destfile="${dist}/shadow_fleet.${DSTAMP}${TSTAM}.zip"
         basedir="../.."
     includes="uniforms/*.uniforms localized_text/*.localized_text entities/*.*"
     />
    </target>
</project>
